'use client';

import {
  createContext,
  useContext,
  useEffect,
  useState,
  useCallback,
  useRef,
  type ReactNode,
} from 'react';
import { Cavos } from '../Cavos';
import { CavosAuth } from '../auth/CavosAuth';
import type { Identity } from '../auth/AuthProvider';
import type { StarknetNetwork } from '../chains/starknet/constants';
import type { ChainCall } from '../chains/ChainAdapter';
import { HttpRecoveryClient } from '../recovery/HttpRecoveryClient';
import { generateRecoveryCode } from '../recovery/BackupSigner';
import { CavosAuthModal } from './CavosAuthModal';

export interface CavosConfig {
  /** Cavos App ID from the dashboard. */
  appId?: string;
  network: StarknetNetwork;
  /** Per-app salt so the same user has distinct wallets per app. */
  appSalt: string;
  /** Cavos paymaster API key (sponsors deploy + execute). */
  paymasterApiKey: string;
  /** Override the Cavos auth backend (self-hosted / staging). */
  authBackendUrl?: string;
  /** Override the Starknet RPC. */
  rpcUrl?: string;
}

export interface CavosModalConfig {
  appName?: string;
  appLogo?: string;
  providers?: ('google' | 'apple' | 'email')[];
  /** How the built-in email provider authenticates. Defaults to magic link. */
  emailMode?: 'magic-link' | 'otp';
  primaryColor?: string;
  /** 'light' (default) or 'dark'. */
  theme?: 'light' | 'dark';
  onSuccess?: (address: string) => void;
}

/** Minimal wallet-status surface the React layer (and modal) needs. */
export interface WalletStatus {
  /** True while the device-signer account is being deployed. */
  isDeploying: boolean;
  /** True once deployed and this device is an authorized signer. */
  isReady: boolean;
  /** True if this device still needs approval to operate the wallet. */
  needsDeviceApproval: boolean;
  /** True while waiting for the owner to approve this device from another device. */
  awaitingApproval: boolean;
  /** The pending device-addition request id, when awaitingApproval. */
  pendingRequestId: string | null;
}

export interface UserInfo {
  userId: string;
  email?: string;
  provider?: string;
}

export interface CavosContextValue {
  /** Open / close the built-in auth modal. */
  openModal: () => void;
  closeModal: () => void;
  isAuthenticated: boolean;
  user: UserInfo | null;
  address: string | null;
  walletStatus: WalletStatus;
  isLoading: boolean;
  /** Last unrecoverable auth/connect error surfaced to the UI (e.g. a failed
   * OAuth callback). Null while things are healthy. Cleared on a new attempt. */
  authError: string | null;
  /** Clear `authError` (e.g. when the user starts a new login attempt). */
  clearAuthError: () => void;
  /** OAuth social login — opens the provider's hosted flow. */
  login: (provider: 'google' | 'apple') => Promise<void>;
  /** Send a passwordless magic-link email. */
  sendMagicLink: (email: string) => Promise<void>;
  /** Send an email OTP code. */
  sendOtp: (email: string) => Promise<void>;
  /** Verify an email OTP / complete a magic link and deploy the wallet. */
  verifyOtp: (email: string, code: string) => Promise<void>;
  /** Resolve identity from an OAuth callback (?auth_data=…) and deploy. */
  handleCallback: (authData: string) => Promise<void>;
  /** Execute a sponsored (gasless) multicall, signed by the device key. */
  execute: (calls: ChainCall[]) => Promise<{ transactionHash: string }>;
  /** Authorize another device signer on this wallet (sponsored add_signer). */
  addSigner: (pubkey: { x: bigint; y: bigint }) => Promise<{ transactionHash: string }>;
  /** Re-request the device-approval email for the current pending request. */
  resendDeviceApproval: () => Promise<void>;
  /**
   * Register a backup signer derived from `code` on the current account
   * (gasless). The code is generated by the kit and shown to the user once.
   * Resolves with the code so the caller can display it.
   */
  setupRecovery: () => Promise<string>;
  /**
   * Recover access after losing every device. Requires the recovery code. Runs
   * the full Cavos.recover flow and brings the provider to a ready state.
   */
  recover: (code: string) => Promise<void>;
  logout: () => void;
}

const CavosContext = createContext<CavosContextValue | null>(null);

export interface CavosProviderProps {
  config: CavosConfig;
  modal?: CavosModalConfig;
  children: ReactNode;
}

const INITIAL_STATUS: WalletStatus = {
  isDeploying: false,
  isReady: false,
  needsDeviceApproval: false,
  awaitingApproval: false,
  pendingRequestId: null,
};

/**
 * Drop-in Cavos provider. Wrap your app once; descendants call `useCavos()`.
 *
 *   <CavosProvider config={{ network: 'sepolia', appSalt, paymasterApiKey }}
 *                  modal={{ appName: 'My App', theme: 'dark', emailMode: 'otp' }}>
 *     <App />
 *   </CavosProvider>
 *
 * Behind the scenes: login (social / email) resolves a stable identity, the kit
 * deploys a device-signer smart account gaslessly, and `execute()` submits
 * gasless multicalls signed silently by the browser's device key.
 */
export function CavosProvider({ config, modal, children }: CavosProviderProps) {
  const [auth] = useState(
    () => new CavosAuth({ appId: config.appId, backendUrl: config.authBackendUrl }),
  );
  const [cavos, setCavos] = useState<Cavos | null>(null);
  const [identity, setIdentity] = useState<Identity | null>(null);
  const [walletStatus, setWalletStatus] = useState<WalletStatus>(INITIAL_STATUS);
  const [isLoading, setIsLoading] = useState(false);
  const [authError, setAuthError] = useState<string | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  /** App name/logo fetched from the backend; overrides manual modal props when present. */
  const [branding, setBranding] = useState<{ appName?: string; appLogo?: string }>({});

  // Keep the latest config for callbacks that run after async gaps.
  const configRef = useRef(config);
  useEffect(() => {
    configRef.current = config;
  }, [config]);

  // Fetch app branding (name, logo) from the backend so the modal shows the
  // integrating app's identity without manual props.
  useEffect(() => {
    if (!config.appId || typeof window === 'undefined') return;
    const base = config.authBackendUrl ?? 'https://cavos.xyz';
    fetch(`${base}/api/oauth/firebase/app-branding?app_id=${encodeURIComponent(config.appId)}`)
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        if (d?.name) setBranding((b) => ({ ...b, appName: d.name }));
        if (d?.logo_url) setBranding((b) => ({ ...b, appLogo: d.logo_url }));
      })
      .catch(() => {});
  }, [config.appId, config.authBackendUrl]);

  const openModal = useCallback(() => setModalOpen(true), []);
  const closeModal = useCallback(() => setModalOpen(false), []);
  const clearAuthError = useCallback(() => setAuthError(null), []);

  // Re-request the device-approval email for the current pending request. The
  // backend dedups within its TTL; calling again re-sends the owner email so the
  // user can recover from a lost/spam-filtered message.
  const resendDeviceApproval = useCallback(async () => {
    if (!identity || !cavos || !cavos.pendingRequestId) return;
    const backendUrl = configRef.current.authBackendUrl ?? 'https://cavos.xyz';
    if (!configRef.current.appId) return;
    const recovery = new HttpRecoveryClient({ baseUrl: backendUrl, appId: configRef.current.appId });
    await recovery.requestDeviceAddition({
      userId: identity.userId,
      accountAddress: cavos.address,
      newSigner: cavos.publicKey,
      ...(identity.email ? { email: identity.email } : {}),
    });
  }, [identity, cavos]);

  // Bring the wallet online for an identity: Cavos.connect deploys if needed.
  const connect = useCallback(async (id: Identity): Promise<Cavos> => {
    setWalletStatus({ ...INITIAL_STATUS, isDeploying: true });
    const c = await Cavos.connect({
      network: configRef.current.network,
      identity: id,
      appSalt: configRef.current.appSalt,
      paymasterApiKey: configRef.current.paymasterApiKey,
      ...(configRef.current.appId ? { appId: configRef.current.appId } : {}),
      ...(configRef.current.authBackendUrl ? { backendUrl: configRef.current.authBackendUrl } : {}),
      ...(configRef.current.rpcUrl ? { rpcUrl: configRef.current.rpcUrl } : {}),
    });
    setCavos(c);
    setIdentity(id);
    setWalletStatus({
      isDeploying: false,
      isReady: c.status === 'ready',
      needsDeviceApproval: c.status === 'needs-device-approval',
      awaitingApproval: c.status === 'needs-device-approval' && !!c.pendingRequestId,
      pendingRequestId: c.pendingRequestId,
    });
    modal?.onSuccess?.(c.address);
    return c;
  }, [modal]);

  // On mount: if we're returning from OAuth (?auth_data=…), finish the login.
  // Open the modal immediately so the user sees the "deploying" state while the
  // wallet is being brought online — it flips to "done" once `isReady`.
  useEffect(() => {
    if (typeof window === 'undefined') return;
    const params = new URLSearchParams(window.location.search);
    const authData = params.get('auth_data') || params.get('zk_auth_data');
    if (!authData) return;
    setModalOpen(true);
    setWalletStatus({ ...INITIAL_STATUS, isDeploying: true });
    let cancelled = false;
    (async () => {
      setIsLoading(true);
      try {
        await handleCallback(authData);
        if (!cancelled) window.history.replaceState({}, document.title, window.location.pathname);
      } catch (e) {
        console.error('[CavosProvider] OAuth callback error:', e);
        if (!cancelled) {
          // Surface the failure instead of closing the modal silently: the user
          // sees an actionable error with a retry, rather than the modal vanishing.
          const msg = e instanceof Error ? e.message : 'Sign-in failed. Please try again.';
          setAuthError(msg);
          setWalletStatus(INITIAL_STATUS);
        }
      } finally {
        if (!cancelled) setIsLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleCallback = useCallback(async (authData: string) => {
    const id = await auth.handleCallback(authData);
    await connect(id);
  }, [auth, connect]);

  const login = useCallback(async (provider: 'google' | 'apple') => {
    if (typeof window === 'undefined') throw new Error('OAuth requires a browser');
    setAuthError(null);
    const url = await (provider === 'google'
      ? auth.getGoogleOAuthUrl(window.location.origin + window.location.pathname)
      : auth.getAppleOAuthUrl(window.location.origin + window.location.pathname));
    window.location.href = url;
  }, [auth]);

  const sendMagicLink = useCallback(async (email: string) => {
    await auth.sendMagicLink(email);
  }, [auth]);

  const sendOtp = useCallback(async (email: string) => {
    await auth.sendOtp(email);
  }, [auth]);

  const verifyOtp = useCallback(async (email: string, code: string) => {
    setAuthError(null);
    const id = await auth.verifyOtp(email, code);
    await connect(id);
  }, [auth, connect]);

  const execute = useCallback(async (calls: ChainCall[]) => {
    if (!cavos) throw new Error('Not logged in');
    return cavos.execute(calls);
  }, [cavos]);

  const addSigner = useCallback(
    async (pubkey: { x: bigint; y: bigint }) => {
      if (!cavos) throw new Error('Not logged in');
      return cavos.addSigner(pubkey);
    },
    [cavos],
  );

  // Generate a recovery code and register its derived backup signer on-chain.
  // The code is returned so the UI can display it once — the kit never persists
  // it and the backend never sees it.
  const setupRecovery = useCallback(async (): Promise<string> => {
    if (!cavos) throw new Error('Not logged in');
    const code = generateRecoveryCode();
    await cavos.setupRecovery(code);
    return code;
  }, [cavos]);

  // Recover access after losing every device. The caller passes the recovery
  // code; the backup key it derives authorises adding this new device. Brings
  // the provider straight to a ready state.
  const recover = useCallback(async (code: string) => {
    if (!identity) throw new Error('Sign in first so we know which account to recover.');
    setAuthError(null);
    setWalletStatus({ ...INITIAL_STATUS, isDeploying: true });
    try {
      const c = await Cavos.recover({
        code,
        identity,
        network: configRef.current.network,
        appSalt: configRef.current.appSalt,
        paymasterApiKey: configRef.current.paymasterApiKey,
        ...(configRef.current.appId ? { appId: configRef.current.appId } : {}),
        ...(configRef.current.authBackendUrl ? { backendUrl: configRef.current.authBackendUrl } : {}),
        ...(configRef.current.rpcUrl ? { rpcUrl: configRef.current.rpcUrl } : {}),
      });
      setCavos(c);
      setWalletStatus({ ...INITIAL_STATUS, isReady: true });
      modal?.onSuccess?.(c.address);
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Recovery failed. Check your code and try again.';
      setAuthError(msg);
      setWalletStatus(INITIAL_STATUS);
      throw e;
    }
  }, [identity, modal]);

  // Poll the pending device-addition request while this device is awaiting the
  // owner's approval. Once the owner approves (status === 'approved'), the new
  // signer is authorized on-chain, so reconnecting flips the device to "ready"
  // automatically — the requester no longer has to sign out and back in.
  useEffect(() => {
    if (!walletStatus.awaitingApproval || !walletStatus.pendingRequestId || !identity) return;
    if (!configRef.current.appId) return;
    const backendUrl = configRef.current.authBackendUrl ?? 'https://cavos.xyz';
    const recovery = new HttpRecoveryClient({ baseUrl: backendUrl, appId: configRef.current.appId });
    const requestId = walletStatus.pendingRequestId;
    let cancelled = false;
    const tick = async () => {
      try {
        const r = await recovery.getPendingRequest(requestId);
        if (cancelled || !r) return;
        if (r.status === 'expired') {
          // Surface expiry so the modal can offer "request a new one".
          setWalletStatus((s) => ({ ...s, pendingRequestId: null }));
          return;
        }
        if (r.status === 'approved') {
          // The owner added this device's signer on-chain — reconnect to flip
          // to "ready" without making the user log in again.
          await connect(identity);
        }
      } catch {
        /* transient network errors are fine; the next tick retries */
      }
    };
    const interval = setInterval(tick, 4000);
    return () => {
      cancelled = true;
      clearInterval(interval);
    };
  }, [walletStatus.awaitingApproval, walletStatus.pendingRequestId, identity, connect]);

  const logout = useCallback(() => {
    setCavos(null);
    setIdentity(null);
    setWalletStatus(INITIAL_STATUS);
    setAuthError(null);
  }, []);

  const value: CavosContextValue = {
    openModal,
    closeModal,
    isAuthenticated: !!cavos,
    user: identity
      ? { userId: identity.userId, email: identity.email, provider: identity.provider }
      : null,
    address: cavos?.address ?? null,
    walletStatus,
    isLoading,
    authError,
    clearAuthError,
    login,
    sendMagicLink,
    sendOtp,
    verifyOtp,
    handleCallback,
    execute,
    addSigner,
    resendDeviceApproval,
    setupRecovery,
    recover,
    logout,
  };

  return (
    <CavosContext.Provider value={value}>
      {children}
      {modal !== undefined && (
        <CavosAuthModal
          open={modalOpen}
          onClose={closeModal}
          appName={branding.appName ?? modal.appName}
          appLogo={branding.appLogo ?? modal.appLogo}
          providers={modal.providers}
          emailMode={modal.emailMode}
          primaryColor={modal.primaryColor}
          theme={modal.theme}
        />
      )}
    </CavosContext.Provider>
  );
}

export function useCavos(): CavosContextValue {
  const ctx = useContext(CavosContext);
  if (!ctx) throw new Error('useCavos must be used within a CavosProvider');
  return ctx;
}
